In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 수집, 탐색

In [3]:
df = pd.read_csv('./data/premium.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
df = df.drop_duplicates()
df.info()

<class 'pandas.DataFrame'>
Index: 1337 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1337 non-null   int64
 1   sex       1337 non-null   str
 2   bmi       1332 non-null   float64
 3   children  1337 non-null   int64
 4   smoker    1337 non-null   str
 5   region    1337 non-null   str
 6   charges   1337 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 83.6 KB

# 전처리

중복체크, 널처리, 인코딩

In [5]:
print(df.bmi.isnull())

0       False
1       False
2       False
3       False
4       False
        ...
1333    False
1334    False
1335    False
1336    False
1337    False
Name: bmi, Length: 1337, dtype: bool

In [6]:
df['bmi'] = df['bmi'].fillna(df['bmi'].mean())

In [7]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
# 문자열 데이터의 수치화 > LabelEncoder
col_list = ['sex', 'smoker', 'region']
for col in col_list: 
  enc = LabelEncoder()
  df[col] = enc.fit_transform(df[col])
  
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

# 분할하기

In [10]:
X = df.iloc[:,:-1]
y = df.iloc[:, -1]

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.2, random_state=42)

# 스케일링 하기

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train['bmi'] = scaler.fit_transform(X_train[['bmi']])
X_test['bmi'] = scaler.transform(X_test[['bmi']])
X_test['bmi']

900    -1.330419
1064   -0.818614
1256    0.970629
298     0.639656
237     1.303260
          ...
534     1.649993
542     0.956527
760     0.671177
1284    0.956527
1285   -1.030968
Name: bmi, Length: 268, dtype: float64

# 선형회귀 모델

In [13]:

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
y_pred = lr_model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
mae, mse, rmse, r2

(4170.6423560015255,
 35550130.517054714,
 np.float64(5962.393019338352),
 0.8065362865570331)

# 다항회귀 모델

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline

In [15]:
degree = [2, 3, 4]

for deg in degree:
    model_poly = Pipeline([
        ('poly', PolynomialFeatures(degree=deg, include_bias=False)),
        ('linear', LinearRegression())
    ])
    
    model_poly.fit(X_train, y_train)
    poly_pred = model_poly.predict(X_test)
    
    mae = mean_absolute_error(y_test, poly_pred)
    mse = mean_squared_error(y_test, poly_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, poly_pred)
    
    print(f'Degree {degree} | MAE: {mae:.4f} | MSE: {mse:.4f} | RMSE: {rmse:.4f} | R^2: {r2:.4f}')

Degree [2, 3, 4] | MAE: 2838.2869 | MSE: 20879449.3187 | RMSE: 4569.4036 | R^2: 0.8864
Degree [2, 3, 4] | MAE: 3021.4520 | MSE: 22521905.9297 | RMSE: 4745.7250 | R^2: 0.8774
Degree [2, 3, 4] | MAE: 3245.7158 | MSE: 26691158.4155 | RMSE: 5166.3487 | R^2: 0.8547

In [16]:
from sklearn.ensemble import RandomForestRegressor
model_rf = RandomForestRegressor(n_estimators=100, random_state= 0)
model_rf.fit(X_train, y_train)
y_pred_rf = model_rf.predict(X_test)
mae = mean_absolute_error(y_test, y_pred_rf)
mse = mean_squared_error(y_test, y_pred_rf)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred_rf)
mae, mse, rmse, r2

(2597.4139290194025,
 21900427.796358738,
 np.float64(4679.7892897393085),
 0.8808179315842309)

In [17]:
import pandas as pd
feature_names = ['age', 'sex', 'bmi', 'children', 'smoker', 'region']
importance_df = pd.DataFrame({
  "feature" : feature_names,
  'importance' : model_rf.feature_importances_
}).sort_values('importance', ascending= False)

print('\n--- 특성 중요도 ---')
print(importance_df)

--- 특성 중요도 ---
    feature  importance
4    smoker    0.600497
2       bmi    0.212468
0       age    0.138651
3  children    0.024268
5    region    0.016831
1       sex    0.007285

In [18]:
#XGBRegressor
from xgboost import XGBRegressor

xgb_reg = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=0
)

xgb_reg.fit(X_train, y_train)
poly_pred = xgb_reg.predict(X_test)

mae = mean_absolute_error(y_test, poly_pred)
mse = mean_squared_error(y_test, poly_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, poly_pred)
    
print(f'MAE: {mae:.4f} | MSE: {mse:.4f} | RMSE: {rmse:.4f} | R^2: {r2:.4f}')

MAE: 2631.0079 | MSE: 19747411.6369 | RMSE: 4443.8060 | R^2: 0.8925

# 하이퍼파라미터 탐색

In [19]:
import optuna
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'max_depth': trial.suggest_int('max_depth', 3, 15),
        'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 5),
        'random_state': 0
    }
    model = RandomForestRegressor(**params)
    score = -cross_val_score(model, X, y, cv=5, scoring='neg_mean_absolute_error').mean()
    return score

study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=50)

print(f'Best MAE : {round(study.best_value, 4)}')
print(f'Best Params : {study.best_params}')

[I 2026-03-03 11:32:32,331] A new study created in memory with name: no-name-f4d93770-3b95-41a7-a3ed-35dfff1d7d8a
[I 2026-03-03 11:32:32,895] Trial 0 finished with value: 2606.317332326284 and parameters: {'n_estimators': 95, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 0 with value: 2606.317332326284.
[I 2026-03-03 11:32:33,646] Trial 1 finished with value: 2569.2395923415215 and parameters: {'n_estimators': 139, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 1 with value: 2569.2395923415215.
[I 2026-03-03 11:32:33,903] Trial 2 finished with value: 2519.865620792829 and parameters: {'n_estimators': 56, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 2 with value: 2519.865620792829.
[I 2026-03-03 11:32:34,975] Trial 3 finished with value: 2605.617143726918 and parameters: {'n_estimators': 165, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 2}. Best is trial 2 with value: 2519.865620792829.
[I 2026-03-03 11:32:35,860] Trial 4 finished with value: 2549.90449497381 and parameters: {'n_estimators': 146, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 2 with value: 2519.865620792829.
[I 2026-03-03 11:32:36,798] Trial 5 finished with value: 2536.616372525947 and parameters: {'n_estimators': 164, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 5}. Best is trial 2 with value: 2519.865620792829.
[I 2026-03-03 11:32:37,951] Trial 6 finished with value: 2572.005772705684 and parameters: {'n_estimators': 190, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 2 with value: 2519.865620792829.
[I 2026-03-03 11:32:38,478] Trial 7 finished with value: 2544.968538475724 and parameters: {'n_estimators': 84, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 5}. Best is trial 2 with value: 2519.865620792829.
[I 2026-03-03 11:32:39,084] Trial 8 finished with value: 2580.6303747965494 and parameters: {'n_estimators': 91, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 2 with value: 2519.865620792829.
[I 2026-03-03 11:32:40,312] Trial 9 finished with value: 2559.4450567797603 and parameters: {'n_estimators': 198, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 2 with value: 2519.865620792829.
[I 2026-03-03 11:32:41,506] Trial 10 finished with value: 2685.9730778031967 and parameters: {'n_estimators': 291, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 2 with value: 2519.865620792829.
[I 2026-03-03 11:32:42,523] Trial 11 finished with value: 2686.7547958194737 and parameters: {'n_estimators': 248, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 2 with value: 2519.865620792829.
[I 2026-03-03 11:32:42,860] Trial 12 finished with value: 2489.8586808745285 and parameters: {'n_estimators': 68, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:43,134] Trial 13 finished with value: 2498.1636014591895 and parameters: {'n_estimators': 54, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:43,395] Trial 14 finished with value: 2498.0761972017453 and parameters: {'n_estimators': 51, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:44,068] Trial 15 finished with value: 2521.764207151333 and parameters: {'n_estimators': 126, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:44,596] Trial 16 finished with value: 2503.497345806633 and parameters: {'n_estimators': 107, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:44,929] Trial 17 finished with value: 2519.041595416212 and parameters: {'n_estimators': 57, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:46,353] Trial 18 finished with value: 2608.624682247134 and parameters: {'n_estimators': 217, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:46,873] Trial 19 finished with value: 2537.9855912705257 and parameters: {'n_estimators': 115, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 3}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:47,334] Trial 20 finished with value: 2545.2949662416895 and parameters: {'n_estimators': 73, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:47,598] Trial 21 finished with value: 2497.5547062790774 and parameters: {'n_estimators': 50, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:47,954] Trial 22 finished with value: 2489.8586808745285 and parameters: {'n_estimators': 68, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:48,411] Trial 23 finished with value: 2524.535652809386 and parameters: {'n_estimators': 77, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:48,903] Trial 24 finished with value: 2527.593971918972 and parameters: {'n_estimators': 105, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:49,306] Trial 25 finished with value: 2509.655534106684 and parameters: {'n_estimators': 73, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:49,850] Trial 26 finished with value: 2690.5965229042413 and parameters: {'n_estimators': 128, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:50,327] Trial 27 finished with value: 2575.6851302889145 and parameters: {'n_estimators': 74, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:50,810] Trial 28 finished with value: 2499.593781127339 and parameters: {'n_estimators': 95, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:51,383] Trial 29 finished with value: 2537.3013899013304 and parameters: {'n_estimators': 95, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:52,668] Trial 30 finished with value: 2566.6972453696426 and parameters: {'n_estimators': 237, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:52,929] Trial 31 finished with value: 2499.4246112102905 and parameters: {'n_estimators': 50, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:53,333] Trial 32 finished with value: 2520.2309683883714 and parameters: {'n_estimators': 69, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:53,639] Trial 33 finished with value: 2522.8600144684774 and parameters: {'n_estimators': 65, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 4}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:53,913] Trial 34 finished with value: 2508.445890363856 and parameters: {'n_estimators': 50, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:54,629] Trial 35 finished with value: 2502.0116232126716 and parameters: {'n_estimators': 144, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:55,024] Trial 36 finished with value: 2525.565841276484 and parameters: {'n_estimators': 87, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:55,441] Trial 37 finished with value: 2549.74587923807 and parameters: {'n_estimators': 64, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 4}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:56,086] Trial 38 finished with value: 2529.8076747983914 and parameters: {'n_estimators': 117, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:56,753] Trial 39 finished with value: 2689.9766077042887 and parameters: {'n_estimators': 164, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:57,204] Trial 40 finished with value: 2507.924356489277 and parameters: {'n_estimators': 84, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 4}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:57,489] Trial 41 finished with value: 2493.495201725367 and parameters: {'n_estimators': 57, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:57,774] Trial 42 finished with value: 2521.770203900287 and parameters: {'n_estimators': 62, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:58,030] Trial 43 finished with value: 2497.5547062790774 and parameters: {'n_estimators': 50, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:58,413] Trial 44 finished with value: 2526.5049295466006 and parameters: {'n_estimators': 84, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:58,759] Trial 45 finished with value: 2506.5693164513964 and parameters: {'n_estimators': 63, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:59,349] Trial 46 finished with value: 2536.8734775171274 and parameters: {'n_estimators': 102, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:32:59,738] Trial 47 finished with value: 2498.1808291067296 and parameters: {'n_estimators': 78, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:33:00,898] Trial 48 finished with value: 2685.770189241889 and parameters: {'n_estimators': 290, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 12 with value: 2489.8586808745285.
[I 2026-03-03 11:33:01,273] Trial 49 finished with value: 2536.874823202904 and parameters: {'n_estimators': 60, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 12 with value: 2489.8586808745285.

Best MAE : 2489.8587
Best Params : {'n_estimators': 68, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 5}

In [27]:
from sklearn.ensemble import RandomForestRegressor

best_model = RandomForestRegressor(
    **study.best_params,
    random_state=0
)

best_model.fit(X, y)

RandomForestRegressor(max_depth=5, min_samples_leaf=5, min_samples_split=7,
                      n_estimators=68, random_state=0)

In [28]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred = best_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"MAE : {mae:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"R2 : {r2:.4f}")

MAE : 5010.0570
RMSE : 9236.2124
R2 : 0.5358